INSERT INTO `TOPICS` (`TITLE`, `DESCRIPTION`) VALUES 
('Java', 'Java est un langage de programmation de haut niveau, basé sur les classes et orienté objet.'),
('Spring', 'Spring est un framework puissant et riche en fonctionnalités pour développer des applications Java.'),
('Python', 'Python est un langage de programmation polyvalent et de haut niveau, connu pour sa simplicité et sa lisibilité.'),
('JavaScript', 'JavaScript est un langage largement utilisé pour le développement web, permettant du contenu dynamique et interactif.'),
('C++', 'C++ est un langage de programmation puissant et performant, souvent utilisé dans la programmation système et le développement de jeux.'),
('Ruby on Rails', 'Ruby on Rails est un framework web populaire écrit en Ruby, connu pour son approche "convention over configuration".'),
('Django', 'Django est un framework web Python de haut niveau qui encourage le développement rapide et un design propre et pragmatique.'),
('Node.js', 'Node.js est un environnement d''exécution JavaScript permettant l''exécution de code côté serveur.'),
('React', 'React est une bibliothèque JavaScript pour construire des interfaces utilisateur, en particulier des applications monopages.'),
('Vue.js', 'Vue.js est un framework JavaScript progressif utilisé pour créer des applications web interactives.'),
('Angular', 'Angular est un framework d''application web basé sur TypeScript, maintenu par Google.'),
('SQL', 'SQL (Structured Query Language) est utilisé pour gérer et interroger des bases de données relationnelles.'),
('NoSQL', 'Les bases de données NoSQL offrent un mécanisme de stockage et de récupération des données différent des bases relationnelles.'),
('GraphQL', 'GraphQL est un langage de requête pour les API permettant de récupérer exactement les données nécessaires depuis un serveur.'),
('Rust', 'Rust est un langage de programmation système axé sur la sécurité, la rapidité et la concurrence.'),
('Go', 'Go (Golang) est un langage typé statiquement conçu pour la simplicité et l''efficacité, souvent utilisé dans le cloud computing.'),
('Kotlin', 'Kotlin est un langage de programmation moderne fonctionnant sur la JVM et officiellement pris en charge pour le développement Android.'),
('Swift', 'Swift est un langage de programmation puissant et intuitif développé par Apple pour les applications iOS et macOS.'),
('PHP', 'PHP est un langage de script côté serveur conçu pour le développement web, mais également utilisé en programmation générale.'),
('C#', 'C# est un langage moderne et orienté objet développé par Microsoft, souvent utilisé dans les applications d''entreprise et les jeux sous Unity.'),
('Machine Learning', 'L''apprentissage automatique est un domaine de l''intelligence artificielle permettant aux systèmes d''apprendre à partir des données sans programmation explicite.'),
('Cybersecurity', 'La cybersécurité regroupe les technologies, processus et contrôles destinés à protéger les systèmes, réseaux et données contre les cybermenaces.');


INSERT INTO `USERS` (`USERNAME`, `EMAIL`, `PASSWORD`) VALUES  
('user1', 'user1@test.com', '$2a$10$Y5KWtorVwUbuE.FraqTBD.hJIT7CcfgFNd7C./u.5N6BkScPF3ipq'),  
('user2', 'user2@test.com', '$2a$10$AiNQzm8AgoUr/JeA7GSUTe3FMZ9nCnXV1R12ZlDZF0K/q.YtqdAEK'),  
('user3', 'user3@test.com', '$2a$10$gR/lbWNP3rc6Sr/cDcLeRe2NzdJ4dvvt45ZFvyWRHRYxZ32V35Kyi'),  
('user4', 'user4@test.com', '$2a$10$cG39Qg2axZKjh5Wns5aAfOsqFdm4xdkUnmqO7eUHYt0xy10gTTuA.'),  
('user5', 'user5@test.com', '$2a$10$bvPPcABZ.3M1LkqG1NDNtOeujYLOuUWqwacl2gPUF7ibu5d0DNu2u'),  
('user6', 'user6@test.com', '$2a$10$KCLYD0vE.IL2bU0X97UXf.rVd7i/8vkDkp98/ilCJj/grCnLkEl6a'),  
('user7', 'user7@test.com', '$2a$10$qAvDdYvRfVbWzGVrfScFyeXDmHsotoERh7DtQVe1SRo1HowZryvei'),  
('user8', 'user8@test.com', '$2a$10$qc8oB7Dfzmi7F2Rxu8nfrep96qOiWnj26d7k0N08x1px5E7RZhqjO'),  
('user9', 'user9@test.com', '$2a$10$rKEpMPAklC.LMk/QMbt/0O3y2/AsGQyax.AtPd5Bqht.ITT6BGNZy'),  
('user10', 'user10@test.com', '$2a$10$bk3w11HKIcZ6Q5wkNRwafeWFDwv5SamPxEL/eKWg6L.zcQemgFvda'),  
('user11', 'user11@test.com', '$2a$10$Ms1BwDg5HscRuLCZV0ov2uDaaZaxDDnCiu/3F/6sapupdpqTt1Nlu'),  
('user12', 'user12@test.com', '$2a$10$AxHYXbQBNmWhHnEnizR44OmMSMlf4BlpIOZ1RDJwYc3Urvx3fZaOu'),  
('user13', 'user13@test.com', '$2a$10$67V45cgzfiYicqlSxyt5TuZy3mlxTiskguRPWTUXeUgHd4isxjIya'),  
('user14', 'user14@test.com', '$2a$10$PgFpU5SEfkN4ClGTeMvXsOvXIDEKt20DUNuWtgQW2jeF4qCv45yce'),  
('user15', 'user15@test.com', '$2a$10$6B/yKs0aoErk9PJUXLI9Gei8n7aZOGTegxCGeVvlyclsovYTGpX0u'),  
('user16', 'user16@test.com', '$2a$10$dU7gMaanxNzxLnSuEvyCQOk1l9cVoP0zWDiLXtBG858ttFQY0zcB6'),  
('user17', 'user17@test.com', '$2a$10$ovJBEy/w9HYwbUh8ioibR.NCzkwlNKhvjVLqJWMnwJrH8R6MXtM9q'),  
('user18', 'user18@test.com', '$2a$10$klKmA7tP4DUQnMUnI7Z8aeIZ0dMlbgFPOzAKJzBG7EY8i/zFBEQ5W'),  
('user19', 'user19@test.com', '$2a$10$U1DpEnSXBg28krT29Ib62erk9lx0aGtzjw62hE7wFwxALr9Z1/sfW'),  
('user20', 'user20@test.com', '$2a$10$7KHWXC21IDwBSl5jcSKtN.GrKBTWNlZO4HuyrUgVaGi7P4UxNlmny'),  
('user21', 'user21@test.com', '$2a$10$XIKDpqTOFwjJHrRGfr0MyeVrUeG/91OK/JpOmOmb2sHfVdYHDuMr6'),  
('user22', 'user22@test.com', '$2a$10$KfDRZqGyygyVaMCnkOjCl.wYouzV00OoO5BJMPiuc4MGfReCqHzZ6'),  
('user23', 'user23@test.com', '$2a$10$Rw3s3ugHllsqsdTMIsHwZONUMzQSlP3IgLdWadBTBH3Tm2TVg.wHm'),  
('user24', 'user24@test.com', '$2a$10$aBhD3ZI7G4gVbQGqragCo.IbrBN6mIyyoh9CEX2juiEoxO3a0Ve6G'),  
('user25', 'user25@test.com', '$2a$10$2ODz5q04xJyyad1ddQZZCOSbzNK3IgxgecA9kD9tDbKPaEN8oU1Ki');  


INSERT INTO `SUBSCRIPTIONS` (`TOPICS_ID`, `USER_ID`) VALUES
(1, 1),
(1, 18);

INSERT INTO `POSTS` (`title`, `content`, `topic_id`, `author_id`, `created_at`) VALUES  
('Introduction à Java', 'Java est un langage de programmation populaire utilisé pour le developpement d''applications d''entreprise, mobiles et web.', 1, 1, '2024-12-08 14:30:15'),
('Les classes et objets en Java', 'Découvrez comment créer et utiliser des classes et objets en Java pour une programmation orientée objet efficace.', 1, 1, '2024-12-05 14:30:15'),
('Introduction à Spring', 'Spring est un framework Java puissant facilitant le développement d''applications robustes et évolutives.', 2, 2, CURRENT_TIMESTAMP()),  
('Spring Boot : Démarrage rapide', 'Spring Boot simplifie le développement des applications Spring en réduisant la configuration nécessaire.', 2, 2, CURRENT_TIMESTAMP()),  
('Les bases de Python', 'Python est un langage facile à apprendre, idéal pour les débutants et puissant pour les experts.', 3, 3, CURRENT_TIMESTAMP()),  
('Gestion des fichiers en Python', 'Apprenez à lire, écrire et manipuler des fichiers avec Python.', 3, 3, CURRENT_TIMESTAMP()),  
('Introduction à JavaScript', 'JavaScript est le langage incontournable pour le développement web interactif.', 4, 4, CURRENT_TIMESTAMP()),  
('Manipulation du DOM avec JavaScript', 'Découvrez comment JavaScript permet de modifier dynamiquement les éléments HTML.', 4, 4, CURRENT_TIMESTAMP()),  
('Les pointeurs en C++', 'Les pointeurs sont un concept essentiel en C++ permettant la gestion efficace de la mémoire.', 5, 5, CURRENT_TIMESTAMP()),  
('La programmation orientée objet en C++', 'Apprenez comment utiliser les classes et objets en C++.', 5, 5, CURRENT_TIMESTAMP()),  
('Introduction à Ruby on Rails', 'Ruby on Rails est un framework web populaire basé sur Ruby.', 6, 6, CURRENT_TIMESTAMP()),  
('Les migrations de base de données avec Rails', 'Apprenez à gérer les bases de données avec Active Record.', 6, 6, CURRENT_TIMESTAMP()),  
('Django : Créer votre première application', 'Django facilite la création d''applications web robustes et évolutives.', 7, 7, CURRENT_TIMESTAMP()),  
('Les modèles dans Django', 'Les modèles Django permettent de structurer vos données efficacement.', 7, 7, CURRENT_TIMESTAMP()),  
('Introduction à Node.js', 'Node.js permet d''exécuter du JavaScript côté serveur.', 8, 8, CURRENT_TIMESTAMP()),  
('Gestion des packages avec npm', 'npm est l''outil de gestion de packages de Node.js.', 8, 8, CURRENT_TIMESTAMP()),  
('Développement avec React', 'React est une bibliothèque JavaScript populaire pour les interfaces utilisateur.', 9, 9, CURRENT_TIMESTAMP()),  
('Le state et les props dans React', 'Comprendre le fonctionnement du state et des props dans React.', 9, 9, CURRENT_TIMESTAMP()),  
('Vue.js pour les débutants', 'Vue.js est un framework JavaScript progressif pour la construction d''interfaces utilisateur.', 10, 10, CURRENT_TIMESTAMP()),  
('Les directives Vue.js', 'Découvrez les directives clés de Vue.js comme v-if, v-for et v-bind.', 10, 10, CURRENT_TIMESTAMP()),  
('Angular : Premier projet', 'Angular est un framework complet pour le développement d''applications web modernes.', 11, 11, CURRENT_TIMESTAMP()),  
('Les services et dépendances dans Angular', 'Apprenez à injecter des dépendances et utiliser des services dans Angular.', 11, 11, CURRENT_TIMESTAMP()),  
('Introduction à SQL', 'SQL est utilisé pour manipuler et interroger les bases de données relationnelles.', 12, 12, CURRENT_TIMESTAMP()),  
('Les jointures SQL expliquées', 'Comprendre comment utiliser les jointures SQL pour interroger plusieurs tables.', 12, 12, CURRENT_TIMESTAMP()),  
('Introduction aux bases de données NoSQL', 'NoSQL propose une alternative flexible aux bases de données relationnelles.', 13, 13, CURRENT_TIMESTAMP()),  
('Les types de bases NoSQL', 'Découvrez les bases de données NoSQL : clé-valeur, document, colonne et graphe.', 13, 13, CURRENT_TIMESTAMP()),  
('Découverte de GraphQL', 'GraphQL est une alternative REST pour la communication entre le frontend et le backend.', 14, 14, CURRENT_TIMESTAMP()),  
('Les requêtes et mutations en GraphQL', 'Apprenez à utiliser les requêtes et mutations dans GraphQL.', 14, 14, CURRENT_TIMESTAMP()),  
('Introduction à Rust', 'Rust est un langage sécurisé et performant adapté aux systèmes critiques.', 15, 15, CURRENT_TIMESTAMP()),  
('Gestion de la mémoire en Rust', 'Rust propose un modèle de gestion mémoire sans garbage collector.', 15, 15, CURRENT_TIMESTAMP()),  
('Développement en Go', 'Go est un langage rapide et efficace idéal pour le cloud computing.', 16, 16, CURRENT_TIMESTAMP()),  
('Les goroutines en Go', 'Les goroutines permettent une programmation concurrente efficace en Go.', 16, 16, CURRENT_TIMESTAMP()),  
('Kotlin pour Android', 'Kotlin est le langage officiel pour le développement Android.', 17, 17, CURRENT_TIMESTAMP()),  
('Les coroutines en Kotlin', 'Découvrez les coroutines, une solution élégante pour la programmation asynchrone.', 17, 17, CURRENT_TIMESTAMP()),  
('Swift et le développement iOS', 'Swift est un langage puissant et intuitif conçu par Apple.', 18, 18, CURRENT_TIMESTAMP()),  
('Les closures en Swift', 'Apprenez à utiliser les closures pour manipuler les fonctions de manière flexible.', 18, 18, CURRENT_TIMESTAMP()),  
('PHP et le développement web', 'PHP est un langage populaire pour la création de sites web dynamiques.', 19, 19, CURRENT_TIMESTAMP()),  
('Les frameworks PHP : Laravel', 'Laravel est un framework PHP moderne et puissant.', 19, 19, CURRENT_TIMESTAMP()),  
('Introduction à C#', 'C# est un langage puissant utilisé dans le développement d''applications Microsoft et Unity.', 20, 20, CURRENT_TIMESTAMP()),  
('Programmation asynchrone en C#', 'Découvrez le modèle async/await pour la programmation asynchrone en C#.', 20, 20, CURRENT_TIMESTAMP()),  
('Introduction au Machine Learning', 'Le Machine Learning permet aux systèmes d''apprendre à partir des données.', 21, 21, CURRENT_TIMESTAMP()),  
('Les réseaux de neurones artificiels', 'Découvrez le fonctionnement des réseaux de neurones et leur application.', 21, 21, CURRENT_TIMESTAMP()),  
('Cybersecurity : Protéger ses données', 'La cybersécurité est essentielle pour protéger les informations sensibles.', 22, 22, CURRENT_TIMESTAMP()),  
('Les attaques courantes et comment s''en prémunir', 'Découvrez les principales cyberattaques et les meilleures pratiques pour s''en protéger.', 22, 22, CURRENT_TIMESTAMP());  

INSERT INTO `COMMENTS` (`CONTENT`, `POST_ID`, `AUTHOR_ID`, `CREATED_AT`) VALUES 
('Super article, très bien expliqué !', 1, 3, CURRENT_TIMESTAMP()),
('Merci pour ces précisions, j''ai appris beaucoup.', 2, 5, CURRENT_TIMESTAMP()),
('Auriez-vous des ressources supplémentaires à recommander ?', 3, 7, CURRENT_TIMESTAMP()),
('Très utile, merci pour le partage.', 4, 6, CURRENT_TIMESTAMP()),
('J''ai testé le code et il fonctionne parfaitement.', 5, 2, CURRENT_TIMESTAMP()),
('Je ne comprends pas bien cette partie, pouvez-vous détailler ?', 6, 8, CURRENT_TIMESTAMP()),
('Excellent article !', 7, 10, CURRENT_TIMESTAMP()),
('J''avais du mal avec ce concept, merci beaucoup.', 8, 12, CURRENT_TIMESTAMP()),
('Super explication, merci !', 9, 15, CURRENT_TIMESTAMP()),
('C''est clair et concis, bravo.', 10, 14, CURRENT_TIMESTAMP()),
('J''ai une question : comment adapter cela à mon projet ?', 11, 9, CURRENT_TIMESTAMP()),
('Bonne introduction au sujet.', 12, 18, CURRENT_TIMESTAMP()),
('Une vraie mine d''or, merci !', 13, 20, CURRENT_TIMESTAMP()),
('Merci pour cet article très bien structuré.', 14, 22, CURRENT_TIMESTAMP()),
('Je n''avais jamais vu cette approche avant, intéressant.', 15, 25, CURRENT_TIMESTAMP()),
('Article très instructif.', 16, 1, CURRENT_TIMESTAMP()),
('Ce serait bien d''avoir un exemple supplémentaire.', 17, 4, CURRENT_TIMESTAMP()),
('Très clair, merci !', 18, 11, CURRENT_TIMESTAMP()),
('J''ai appris quelque chose de nouveau aujourd''hui.', 19, 23, CURRENT_TIMESTAMP()),
('Bonne synthèse du sujet.', 20, 13, CURRENT_TIMESTAMP()),
('Une explication simple et efficace.', 21, 17, CURRENT_TIMESTAMP()),
('J''adore ce genre de contenu, continuez !', 22, 19, CURRENT_TIMESTAMP()),
('Merci pour ce partage !', 23, 24, CURRENT_TIMESTAMP()),
('Petite question : cela fonctionne-t-il aussi avec X ?', 24, 16, CURRENT_TIMESTAMP()),
('Génial, merci !', 25, 21, CURRENT_TIMESTAMP()),
('Très bien expliqué, bravo.', 26, 5, CURRENT_TIMESTAMP()),
('J''ai essayé, et ça fonctionne bien.', 27, 8, CURRENT_TIMESTAMP()),
('Super utile, merci encore.', 28, 3, CURRENT_TIMESTAMP()),
('Un article clair et précis.', 29, 2, CURRENT_TIMESTAMP()),
('Cela m''a aidé pour mon projet.', 30, 6, CURRENT_TIMESTAMP()),
('Parfaitement expliqué.', 31, 7, CURRENT_TIMESTAMP()),
('J''avais des doutes, mais cet article m''a aidé.', 32, 9, CURRENT_TIMESTAMP()),
('Continuez ainsi, excellent travail.', 33, 12, CURRENT_TIMESTAMP()),
('Merci pour cette explication détaillée.', 34, 18, CURRENT_TIMESTAMP()),
('Un bon récapitulatif du sujet.', 35, 10, CURRENT_TIMESTAMP()),
('J''apprécie le niveau de détail.', 36, 14, CURRENT_TIMESTAMP()),
('Très utile pour les débutants.', 37, 22, CURRENT_TIMESTAMP()),
('Cela m''a beaucoup aidé.', 38, 1, CURRENT_TIMESTAMP()),
('Article très bien écrit.', 39, 11, CURRENT_TIMESTAMP()),
('J''ai testé et ça fonctionne bien.', 40, 16, CURRENT_TIMESTAMP()),
('Merci pour ce tutoriel.', 41, 19, CURRENT_TIMESTAMP()),
('C''est exactement ce que je cherchais.', 42, 21, CURRENT_TIMESTAMP()),
('Une explication claire et précise.', 43, 23, CURRENT_TIMESTAMP()),
('J''ai adoré cet article.', 44, 13, CURRENT_TIMESTAMP());

