DROP TABLE IF EXISTS `SUBSCRIPTIONS`;
DROP TABLE IF EXISTS `COMMENTS`;
DROP TABLE IF EXISTS `POSTS`;
DROP TABLE IF EXISTS `USERS`;
DROP TABLE IF EXISTS `TOPICS`;


CREATE TABLE IF NOT EXISTS `USERS` (
  `id` BIGINT PRIMARY KEY AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL UNIQUE,
  `email` VARCHAR(255) NOT NULL UNIQUE,
  `password` VARCHAR(255) NOT NULL
  );

CREATE TABLE IF NOT EXISTS `TOPICS` (
  `id` BIGINT PRIMARY KEY AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL UNIQUE,
  `description` VARCHAR(255) NOT NULL
  );

CREATE TABLE IF NOT EXISTS `POSTS` (
  `id` BIGINT PRIMARY KEY AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL UNIQUE,
  `content` VARCHAR(255) NOT NULL,
  `topic_id` BIGINT NOT NULL,
  `author_id` BIGINT NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  FOREIGN KEY (`author_id`) REFERENCES `USERS` (`id`),
  FOREIGN KEY (`topic_id`) REFERENCES `TOPICS` (`id`)
);

CREATE TABLE IF NOT EXISTS `COMMENTS` (
  `id` BIGINT PRIMARY KEY AUTO_INCREMENT,
  `content` VARCHAR(255) NOT NULL,
  `post_id` BIGINT NOT NULL,
  `author_id` BIGINT NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  FOREIGN KEY (`post_id`) REFERENCES `POSTS` (`id`),
  FOREIGN KEY (`author_id`) REFERENCES `USERS` (`id`)
);

CREATE TABLE IF NOT EXISTS `SUBSCRIPTIONS` (
  `topics_id` BIGINT NOT NULL,
  `user_id` BIGINT NOT NULL,
  PRIMARY KEY (`topics_id`, `user_id`),
  FOREIGN KEY (`topics_id`) REFERENCES `TOPICS` (`id`),
  FOREIGN KEY (`user_id`) REFERENCES `USERS` (`id`)
);